### ISSUE TITLE
Bump up minimum Terraform version to 1.0

### ISSUE THREAD

**Issue by pimielowski** [PaloAltoNetworks/terraform-google-vmseries-modules#144] opened 2022-11-29 12:00 UTC
### Is your feature request related to a problem?

Since we popping up the minimum Terraform version in AzureRM modules. there is a good moment to bump up TF version on our repositories.

### Describe the solution you'd like

Bump up min TF version in whole code stack

**Comment by migara** [comment] 2023-03-01 11:29
Duplicate of https://github.com/PaloAltoNetworks/terraform-google-vmseries-modules/issues/156

**Closed by migara** 2023-03-01 11:29 UTC
Labels: enhancement
