### ISSUE TITLE
Conditional support for Panorama logging disk

### ISSUE THREAD

**Issue by seanyoungberg** [PaloAltoNetworks/terraform-google-vmseries-modules#30] opened 2020-11-09 16:29 UTC
We need to have support for n number of logging disks to attach to each panorama VM.

Some customers will be running management-only mode without any logging disks.

Most commonly, customers will start with a single 2TB disk but need the option to later attach additional disks if needed for more space. Due to limitations of panorama, it can only grow logging capacity by attaching these disks in 2TB increments.

**Comment by migara** [comment] 2022-05-19 12:55
Duplicate of #29

**Closed by migara** 2022-05-19 12:55 UTC
Labels: enhancement
